### ISSUE TITLE
Fix jbennett's assignment one repo specification 

### ISSUE THREAD

**Issue by machawk1** [machawk1/ODUCS418#15]
@jbennett122, the repository you defined in the file submitted with https://github.com/machawk1/ODUCS418/blob/spring2015/users/jbennett for assignment 1 specified your fork of the class repository and not your CS418 project repository. I presume https://github.com/jbennett122/JBENNETT_CS418 is what you wanted to include in the file. Is this correct? If so, I can make the change on this end.

**Comment by jbennett122** [comment]
Yes it is. I thought I had the correct link copied and was in a rush. Much appreciated.

**Comment by machawk1** [comment]
Thanks for the confirmation. I have applied the change to the file you submitted for assignment 1.
